### ISSUE TITLE
Can't pull image from platform registry

### ISSUE THREAD

**Issue by Dadacticiel** [lando/platformsh#169]

**Comment by aimfeld** [comment]
Same issue here, when specifying mysql 10.6 or redis 7.0 in services.yml, I get the same error. Mysql 10.5 and redis 6.2 works for me though.

**Comment by artiswilliams** [comment]
I'm experiencing this issue for mariadb 10.6.

**Comment by thewheat** [comment]
If you're encountering this, try specifying an image with a `stable` tag as detailed here https://github.com/lando/platformsh/issues/163#issuecomment-1122262912 

> 
> **Update**: The stable image can be used by an override in the .lando.yml as described in https://docs.lando.dev/guides/overriding-a-service-version.html.
> In the case of php 8.0 will look like that:

```
services:
    app:
        overrides:
            image: docker.registry.platform.sh/php-8.0:stable
```


Manually trying to pull MySQL 10.6 and Redis 7.0 and if the default tag is `latest` it does throw a 403 response. Using `stable` works as shown in the output below

```
$ docker pull docker.registry.platform.sh/mysql-10.6
Using default tag: latest
Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>MMJ7S9JF75NYHMDH</RequestId><HostId>hlH9R6qHEXgd8InTNHG7NPCWv96I4qfxSAgOueDI90XtOYxn7H853vIUnrJFSuyaRkQW3X0GAMc=</HostId></Error>"

$ docker pull docker.registry.platform.sh/mysql-10.6:stable
stable: Pulling from mysql-10.6
...

$ docker pull docker.registry.platform.sh/redis-7.0
Using default tag: latest
Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>R6A092FTCT55PG9F</RequestId><HostId>tkEycOT55/HzkHuz697rHwLKTAT+RPycjj2Kw1EWCCXmEYxoJ2R/rnHYhKs0ylTnm/FP13qw8U4=</HostId></Error>"

$ docker pull docker.registry.platform.sh/redis-7.0:stable
stable: Pulling from redis-7.0
2fccf0ed7151: Pulling fs layer
...
```

**Comment by josemilioz** [comment]
When I attempt to use php-8.3:stable it fails during the rebuilding process.

The .platform.app.yml starts like this:
`
# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: "php:8.3"
`

But as I run Lando, I get the usual Access denied, you need to docker login blah blah.

So, when I try to override the the image on my .lando.yml with the following
`
services:
  app:
    overrides:
      image: "docker.registry.platform.sh/php-8.3:stable"
`

I get this output after hitting lando rebuild -y

`
Opening platform.sh containers... this may take a bit...
ERROR ==> 2025-01-24 21:24:35,373 platformsh.agent DEBUG Running: /etc/platform/commands/open
2025-01-24 21:24:35,449 platformsh.agent.service DEBUG Entering AppService.open
2025-01-24 21:24:35,485 platformsh.agent.service DEBUG Implementing document root inheritance
2025-01-24 21:24:35,485 platformsh.agent.service DEBUG Disabling script execution under mounts by default
2025-01-24 21:24:35,485 platformsh.agent.service DEBUG Root dir lookup mapping: OrderedDict([('wordpress', ['/']), ('wordpress/wp-content/cache', ['/wp-content/cache']), ('wordpress/wp-content/uploads', ['/wp-content/uploads'])])
2025-01-24 21:24:35,485 platformsh.agent.service DEBUG Disabling script execution for mount: "wordpress/wp-content/cache"
2025-01-24 21:24:35,485 platformsh.agent.service DEBUG No match for parent path wordpress/wp-content
2025-01-24 21:24:35,485 platformsh.agent.service DEBUG Parent path "wordpress" matched, adding locations ['/']
2025-01-24 21:24:35,485 platformsh.agent.service DEBUG No match for parent path 
2025-01-24 21:24:35,485 platformsh.agent.service DEBUG Checking location /
2025-01-24 21:24:35,486 platformsh.agent.service DEBUG Mount location prefix /wp-content/cache already in locations
2025-01-24 21:24:35,486 platformsh.agent.service DEBUG Disabling script execution for mount: "wordpress/wp-content/uploads"
2025-01-24 21:24:35,486 platformsh.agent.service DEBUG No match for parent path wordpress/wp-content
2025-01-24 21:24:35,486 platformsh.agent.service DEBUG Parent path "wordpress" matched, adding locations ['/']
2025-01-24 21:24:35,486 platformsh.agent.service DEBUG No match for parent path 
2025-01-24 21:24:35,486 platformsh.agent.service DEBUG Checking location /
2025-01-24 21:24:35,486 platformsh.agent.service DEBUG Mount location prefix /wp-content/uploads already in locations
2025-01-24 21:24:35,486 platformsh.agent.service DEBUG Done disabling script execution under mounts by default
2025-01-24 21:24:35,490 platformsh.agent.service INFO Loading extension dependency information from /etc/platform/php-ext-deps.json
2025-01-24 21:24:35,617 platformsh.agent.util DEBUG b'Failed to connect to bus: No such file or directory\n'
2025-01-24 21:24:35,618 platformsh.agent ERROR Error in service config.py:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/platformsh/agent/__init__.py", line 53, in log_and_load
    yield load(**kwargs)
  File "/etc/platform/commands/open", line 17, in <module>
    endpoints = service.open(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/platformsh_app/service.py", line 1150, in open
    self.start_services(self.non_core_services)
  File "/usr/lib/python3/dist-packages/platformsh/agent/service.py", line 691, in start_services
    self.service_start(service)
  File "/usr/lib/python3/dist-packages/platformsh/agent/service.py", line 296, in service_start
    check_call(
  File "/usr/lib/python3/dist-packages/platformsh/agent/util.py", line 213, in check_call
    raise subprocess.CalledProcessError(returncode=proc.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['systemctl', '--user', 'start', 'app']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/etc/platform/commands/open", line 17, in <module>
    endpoints = service.open(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/platformsh_app/service.py", line 1150, in open
    self.start_services(self.non_core_services)
  File "/usr/lib/python3/dist-packages/platformsh/agent/service.py", line 691, in start_services
    self.service_start(service)
  File "/usr/lib/python3/dist-packages/platformsh/agent/service.py", line 296, in service_start
    check_call(
  File "/usr/lib/python3/dist-packages/platformsh/agent/util.py", line 213, in check_call
    raise subprocess.CalledProcessError(returncode=proc.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['systemctl', '--user', 'start', 'app']' returned non-zero exit status 1.
`

**Comment by reynoldsalec** [comment]
Just a note @josemilioz that neither the Platform or Lando teams are maintaining this integration any more.
