### ISSUE TITLE
OSError when rebuilding

### ISSUE THREAD

**Issue by myleswright2** [lando/platformsh#209]
Every time I rebuild my application, I see this error and have to destroy the application to fix it. 

`ERROR ==> 2024-07-09 16:59:52,719 platformsh.agent DEBUG Running: /etc/platform/commands/open
2024-07-09 16:59:52,808 root INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
2024-07-09 16:59:52,897 root INFO Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
2024-07-09 16:59:56,914 platformsh.agent.service DEBUG Entering AppService.open
2024-07-09 16:59:56,915 platformsh.agent.service DEBUG Waiting for services to come online...
2024-07-09 16:59:56,920 platformsh.agent.service DEBUG All services are online.
2024-07-09 16:59:56,920 platformsh.agent.service INFO Initializing service...
2024-07-09 16:59:56,922 platformsh.agent ERROR Error in service config.py:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/platformsh/agent/__init__.py", line 37, in log_and_load
    yield load(**kwargs)
  File "/etc/platform/commands/open", line 17, in <module>
    endpoints = service.open(**kwargs)
  File "/usr/lib/python2.7/dist-packages/platformsh_app/service.py", line 1119, in open
    self.boot_initialize()
  File "/usr/lib/python2.7/dist-packages/platformsh_app/service.py", line 494, in boot_initialize
    self.fix_runit_perms()
  File "/usr/lib/python2.7/dist-packages/platformsh_app/service.py", line 484, in fix_runit_perms
    os.chown("/run/runit/app/supervise", -1, self.web_gid)
OSError: [Errno 2] No such file or directory: '/run/runit/app/supervise'
Traceback (most recent call last):
  File "/etc/platform/commands/open", line 17, in <module>
    endpoints = service.open(**kwargs)
  File "/usr/lib/python2.7/dist-packages/platformsh_app/service.py", line 1119, in open
    self.boot_initialize()
  File "/usr/lib/python2.7/dist-packages/platformsh_app/service.py", line 494, in boot_initialize
    self.fix_runit_perms()
  File "/usr/lib/python2.7/dist-packages/platformsh_app/service.py", line 484, in fix_runit_perms
    os.chown("/run/runit/app/supervise", -1, self.web_gid)
OSError: [Errno 2] No such file or directory: '/run/runit/app/supervise'`

**Comment by myleswright2** [comment]
To fix this, I ran lando rebuild. It did not work every time but on the occasion that it pulled the app container, it did fix the issue.
