### ISSUE TITLE
Platformsh - error on lando start

### ISSUE THREAD

**Issue by markushausammann** [lando/platformsh#48]
I'm setting up lando configurations for a multi application platform.sh instance. This project has four applications, three of which I was able to spin up with lando successfully. What I realised was that the routes were not picked up so I created them with my own `proxy` settings. At that point I didn't know yet that lando should pick them up automatically from the `routes.yaml`.

When trying to start the fourth application, which is the only one with a relationship (mariadb) I get the following error when trying to run `lando start`:

```
Unhandled rejection TypeError: Cannot read property 'split' of undefined
    at /snapshot/lando/build/cli/integrations/lando-platformsh/lib/config.js
    at arrayMap (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:639:23)
    at Function.map (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9580:14)
    at interceptor (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:17046:35)
    at Function.thru (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:8817:14)
    at /snapshot/lando/build/cli/node_modules/lodash/lodash.js:4388:28
    at arrayReduce (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:683:21)
    at baseWrapperValue (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:4387:14)
    at LodashWrapper.wrapperValue (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9072:14)
    at Object.getSyncableRelationships (/snapshot/lando/build/cli/integrations/lando-platformsh/lib/config.js)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/integrations/lando-platformsh/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js)
    at /snapshot/lando/build/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11
```
My guess is that lando does not find the `routes.yaml` and the `services.yaml`.

Why is that, resp. how can I test if that's the case? Any tips on how to trouble shoot this?

**Comment by reynoldsalec** [comment]
I can reinforce that I've talked with a couple users who had @dman-coders' issue: https://github.com/lando/platformsh/issues/48#issuecomment-834082530

Definitely make sure you don't have an orphaned `.lando.yml` file somewhere in a parent directory that's throwing off your work!

**Comment by reynoldsalec** [comment]
Another potential cause of this error is a misconfiguration in your Platform config files, typically in the setup of the relationships.

I'm going to close out this issue because it doesn't seem to be a Lando bug; it's typically misconfiguration OR possible a result of multi-app configs, which are currently unsupported.
