### ISSUE TITLE
Platformsh basic template fails to start

### ISSUE THREAD

**Issue by steviewanders** [lando/platformsh#54]
1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.

`Done`

2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.

`Done`

The **FASTEST** way for us to verify and resolve your bug if for you to [write a functional test that breaks](https://docs.devwithlando.io/dev/testing.html#functional-tests), submit it as a pull request and link to that pull request here.

`^ is a broken link...`

If you are not sure how to do that then please complete as much of the below section as possible

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

`v3.0.26, macOS Big Sur 11.3`

**Tell us about your `.lando.yml`**

```yml
name: hakai-ssg-test
recipe: platformsh
config:
  id: zqmls2lc3q572
```

`.platform/services.yml`

```yml
db:
    type: mariadb:10.4
    disk: 512
```

` .platform/routes.yaml`

```yml
"https://www.{default}/":
  type: upstream
  upstream: "gatsby:http"

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"

"https://backend.{default}/":
    type: upstream
    upstream: "wordpress:http"
```

**Tell us about the command you were running**

Any combination of `lando init` and `lando start` or any `lando <command>` using the above config files produces the error.

```bash
lando init 
lando start
```

**Tell us about the error you got**

Rerun the command that produced your error in `debug` mode. Note that `debug` mode is run like this `lando command -vvv`. Paste in the error and the `~100` lines that proceeded it.

```bash
lando start -vvv
Unhandled rejection TypeError: Cannot read property 'split' of undefined
    at /snapshot/lando/build/cli/integrations/lando-platformsh/lib/config.js
    at arrayMap (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:639:23)
    at Function.map (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9580:14)
    at interceptor (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:17046:35)
    at Function.thru (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:8817:14)
    at /snapshot/lando/build/cli/node_modules/lodash/lodash.js:4388:28
    at arrayReduce (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:683:21)
    at baseWrapperValue (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:4387:14)
    at LodashWrapper.wrapperValue (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9072:14)
    at Object.getSyncableRelationships (/snapshot/lando/build/cli/integrations/lando-platformsh/lib/config.js)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/integrations/lando-platformsh/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js)
    at /snapshot/lando/build/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11
```

**Tell us generally about your bug**

`Just trying to run a Platform.sh template locally - happy to be told I did it the wrong way?`

**Tell us more**

Does this bug prevent you from using lando? `Yes`

**Comment by reynoldsalec** [comment]
Closing out as a dup, when we work on multi-application support this should be resolved.
